/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: JBoss EAP 7.2.0.GA (WildFly Core 6.0.11.Final-redhat-00001) - 2.0.15.Final-redhat-00001
 * Generated at: 2019-06-04 18:46:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp.administration;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class dashboard_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/WEB-INF/include.jsp", Long.valueOf(1559659476137L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftagtail_005ftail_0026_005fid_005ffile_005fcount;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftagtail_005ftail_0026_005fid_005ffile_005fcount = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.release();
    _005fjspx_005ftagPool_005ftagtail_005ftail_0026_005fid_005ffile_005fcount.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JBWEB004248: JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      response.addHeader("X-Powered-By", "JSP/2.3");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("  \r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      //  tiles:insertDefinition
      org.apache.tiles.jsp.taglib.InsertDefinitionTag _jspx_th_tiles_005finsertDefinition_005f0 = (new org.apache.tiles.jsp.taglib.InsertDefinitionTag());
      _jsp_instancemanager.newInstance(_jspx_th_tiles_005finsertDefinition_005f0);
      _jspx_th_tiles_005finsertDefinition_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/jsp/administration/dashboard.jsp(3,0) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_tiles_005finsertDefinition_005f0.setName("defaultTemplate");
      _jspx_th_tiles_005finsertDefinition_005f0.setJspBody(new Helper( 0, _jspx_page_context, _jspx_th_tiles_005finsertDefinition_005f0, null));
      _jspx_th_tiles_005finsertDefinition_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005finsertDefinition_005f0);
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script src=\"");
      if (_jspx_meth_c_005furl_005f1(_jspx_page_context))
        return;
      out.write("\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(document).ready(function() {\t\t\r\n");
      out.write("\t\tgetChartDataCrqByProcess();\r\n");
      out.write("\t\tgetChartDataCrqByType();\t\t\r\n");
      out.write("\t\tredimensionDelScroll();\t\t\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write(" \t$('#radioBtn')\r\n");
      out.write(" \t\t.bind(\"click\", function(){ \r\n");
      out.write(" \t\t\t$(\"#divExterno\").load(\" #Panel_Log\", function(){ \r\n");
      out.write(" \t\t\t\tredimensionDelScroll();\t\t\t\t\t//Botón que recarga la información haciendo juego con la carga de los Scrolls\r\n");
      out.write(" \t\t\t});\r\n");
      out.write(" \t\t});\r\n");
      out.write("\t\r\n");
      out.write("\tfunction redimensionDelScroll(){\r\n");
      out.write(" \t\t$('#Panel_Log').scrollTop($('#Panel_Log')[0].scrollHeight);\t//Manda hacia abajo la barra derecha del Scroll\r\n");
      out.write(" \t\t$('.scroll-pane').jScrollPane();\t\t\t\t//Funcion que hace la carga de los Scrolls, sus estilos\r\n");
      out.write("\t\tvar pane = $('.scroll-pane')\t\t\t\t\t//Función que hace que los Scrolls sean rezisables. \r\n");
      out.write("\t\tpane.jScrollPane({\r\n");
      out.write(" \t\t\tresizeSensor: true\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\t\r\n");
      out.write(" \tsetInterval(cargaPanyScroll,60000);\t\t\t\t\t//Cada Minuto hace la carga en forma automatica.!\r\n");
      out.write("    \r\n");
      out.write("\tfunction cargaPanyScroll(){\r\n");
      out.write("\t\t $(\"#divExterno\").load(\" #Panel_Log\", function(){\r\n");
      out.write("\t \t\t\tredimensionDelScroll();\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//Obtiene json con datos de los diferentes crq's a graficar \r\n");
      out.write("\tfunction getChartDataCrqByProcess() {\r\n");
      out.write("\t\tvar jsonResult;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\turl : '");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/consult/getJSONCountCrqByProcess',\r\n");
      out.write("\t\t\ttype : 'GET',\r\n");
      out.write("\t\t\tsuccess : function(data) {\r\n");
      out.write("\t\t\t\t$.each(data, function(index, value) {\r\n");
      out.write("\t\t\t\t\tvalue.color = '#' + Math.floor(Math.random() * 16777215).toString(16);\r\n");
      out.write("\t\t\t\t\tdata[index] = value;\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tchartConfig1(data);\r\n");
      out.write("\t\t\t\t$.unblockUI();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(jqXHR, textStatus, errorThrown) {\r\n");
      out.write("\t\t\t\t$.unblockUI();\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn jsonResult;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//Creacion de la grafica 2\t\t\r\n");
      out.write("\tfunction getChartDataCrqByType() {\r\n");
      out.write("\t\tvar jsonResult;\r\n");
      out.write("\t\t$.ajax({\r\n");
      out.write("\t\t\ttype : 'GET',\r\n");
      out.write("\t\t\tdataType : 'json',\r\n");
      out.write("\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${pageContext.request.contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/consult/getJSONCountTcrqByType\",\r\n");
      out.write("\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t$.each(result, function(index, value) {\r\n");
      out.write("\t\t\t\t\tvalue.color = '#' + Math.floor(Math.random() * 16777215).toString(16);\r\n");
      out.write("\t\t\t\t\tresult[index] = value;\r\n");
      out.write("\t\t\t\t})\r\n");
      out.write("\t\t\t\tchartConfig2(result);\r\n");
      out.write("\t\t\t\t$.unblockUI();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\terror : function(xhr) { // if error occured\r\n");
      out.write("\t\t\t\t$.unblockUI();\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\treturn jsonResult;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//Configuración de la grafica 1: \r\n");
      out.write("\tfunction chartConfig1(dataprovider) {\r\n");
      out.write("\t\tvar chart = AmCharts.makeChart(\"card1\", {\r\n");
      out.write("\t\t\t\"type\" : \"pie\",\r\n");
      out.write("\t\t\t\"titles\" : [ {\r\n");
      out.write("\t\t\t\t\"text\" : '");
      if (_jspx_meth_spring_005fmessage_005f3(_jspx_page_context))
        return;
      out.write("',\r\n");
      out.write("\t\t\t\t\"size\" : 16,\r\n");
      out.write("\t\t\t\t\"color\" : \"#2c3e50\",\r\n");
      out.write("\t\t\t\t\"font-size\" : \"2em\",\r\n");
      out.write("\t\t\t\t\"font-weight\" : \"bold\"\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\t\"theme\" : \"none\",\r\n");
      out.write("\t\t\t\"innerRadius\" : \"30%\",\r\n");
      out.write("\t\t\t\"labelRadius\": 0,\r\n");
      out.write("\t\t\t\"gradientRatio\" : [ -0.4, -0.4, -0.4, -0.4, -0.4, -0.4, 0, 0.1,\t0.2, 0.1, 0, -0.2, -0.5 ],\r\n");
      out.write("\t\t\t\"dataProvider\" : dataprovider,\r\n");
      out.write("\t\t\t\"balloonText\" : \"[[value]]\",\r\n");
      out.write("\t\t\t\"valueField\" : \"valor\",\r\n");
      out.write("\t\t\t\"titleField\" : \"nombre\",\r\n");
      out.write("\t\t\t\"colorField\" : \"color\",\r\n");
      out.write("\t\t\t\"balloon\" : {\r\n");
      out.write("\t\t\t\t\"drop\" : true,\r\n");
      out.write("\t\t\t\t\"adjustBorderColor\" : false,\r\n");
      out.write("\t\t\t\t\"fontSize\" : 12\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"legend\" : {\r\n");
      out.write("\t\t\t\t\"enabled\" : true,\r\n");
      out.write("\t\t\t\t\"align\" : \"center\",\r\n");
      out.write("\t\t\t\t\"markerType\" : \"circle\"\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"export\" : {\r\n");
      out.write("\t\t\t\t\"enabled\" : true,\r\n");
      out.write("\t\t\t\t\"menu\" : [ {\r\n");
      out.write("\t\t\t\t\t\"class\" : \"export-main\",\r\n");
      out.write("\t\t\t\t\t\"menu\" : [ {\r\n");
      out.write("\t\t\t\t\t\t\"label\" : '");
      if (_jspx_meth_spring_005fmessage_005f4(_jspx_page_context))
        return;
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\"menu\" : [ \"PNG\", \"JPG\", \"CSV\" ]\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t} ]\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\t//Configuración de la grafica 2\r\n");
      out.write("\tfunction chartConfig2(dataprovider) {\r\n");
      out.write("\t\tvar chart = AmCharts.makeChart(\"card2\", {\r\n");
      out.write("\t\t\t\"type\" : \"serial\",\r\n");
      out.write("\t\t\t\"titles\" : [ {\r\n");
      out.write("\t\t\t\t\"text\" : '");
      if (_jspx_meth_spring_005fmessage_005f5(_jspx_page_context))
        return;
      out.write("',\r\n");
      out.write("\t\t\t\t\"size\" : 16,\r\n");
      out.write("\t\t\t\t\"color\" : \"#2c3e50\",\r\n");
      out.write("\t\t\t\t\"font-size\" : \"2em\",\r\n");
      out.write("\t\t\t\t\"font-weight\" : \"bold\"\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\t\"dataProvider\" : dataprovider,\r\n");
      out.write("\t\t\t\"startDuration\" : 2,\r\n");
      out.write("\t\t\t\"valueAxes\" : [ {\r\n");
      out.write("\t\t\t\t\"position\" : \"left\",\r\n");
      out.write("\t\t\t\t\"axisAlpha\" : 0,\r\n");
      out.write("\t\t\t\t\"gridAlpha\" : 0\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\t\"graphs\" : [ {\r\n");
      out.write("\t\t\t\t\"balloonText\" : \"[[category]]: <b>[[Cantidad]]</b>\",\r\n");
      out.write("\t\t\t\t\"colorField\" : \"color\",\r\n");
      out.write("\t\t\t\t\"fillAlphas\" : 10.85,\r\n");
      out.write("\t\t\t\t\"lineAlpha\" : 0.1,\r\n");
      out.write("\t\t\t\t\"type\" : \"column\",\r\n");
      out.write("\t\t\t\t\"topRadius\" : .50,\r\n");
      out.write("\t\t\t\t\"valueField\" : \"Cantidad\"\r\n");
      out.write("\t\t\t} ],\r\n");
      out.write("\t\t\t\"depth3D\" : 60,\r\n");
      out.write("\t\t\t\"angle\" : 10,\r\n");
      out.write("\t\t\t\"chartCursor\" : {\r\n");
      out.write("\t\t\t\t\"categoryBalloonEnabled\" : false,\r\n");
      out.write("\t\t\t\t\"cursorAlpha\" : 0,\r\n");
      out.write("\t\t\t\t\"zoomable\" : false\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"categoryField\" : \"Nombre\",\r\n");
      out.write("\t\t\t\"categoryAxis\" : {\r\n");
      out.write("\t\t\t\t\"gridPosition\" : \"start\",\r\n");
      out.write("\t\t\t\t\"axisAlpha\" : 0,\r\n");
      out.write("\t\t\t\t\"gridAlpha\" : 0\r\n");
      out.write("\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"balloon\" : {\r\n");
      out.write("\t\t\t\t\"drop\" : true,\r\n");
      out.write("\t\t\t\t\"adjustBorderColor\" : false,\r\n");
      out.write("\t\t\t\t\"fontSize\" : 12\r\n");
      out.write("\t\t\t},\r\n");
      out.write("\t\t\t\"export\" : {\r\n");
      out.write("\t\t\t\t\"enabled\" : true,\r\n");
      out.write("\t\t\t\t\"menu\" : [ {\r\n");
      out.write("\t\t\t\t\t\"class\" : \"export-main\",\r\n");
      out.write("\t\t\t\t\t\"menu\" : [ {\r\n");
      out.write("\t\t\t\t\t\t\"label\" : '");
      if (_jspx_meth_spring_005fmessage_005f6(_jspx_page_context))
        return;
      out.write("',\r\n");
      out.write("\t\t\t\t\t\t\"menu\" : [ \"PNG\", \"JPG\", \"CSV\" ]\r\n");
      out.write("\t\t\t\t\t} ]\r\n");
      out.write("\t\t\t\t} ]\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t});\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_spring_005fmessage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f0 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f0.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/administration/dashboard.jsp(32,35) name = code type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f0.setCode("language.tags.0044.01");
    int[] _jspx_push_body_count_spring_005fmessage_005f0 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f0 = _jspx_th_spring_005fmessage_005f0.doStartTag();
      if (_jspx_th_spring_005fmessage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f0[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f0.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f0.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f1(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f1 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f1.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f1.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/administration/dashboard.jsp(36,109) name = code type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f1.setCode("language.tags.0044.02");
    int[] _jspx_push_body_count_spring_005fmessage_005f1 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f1 = _jspx_th_spring_005fmessage_005f1.doStartTag();
      if (_jspx_th_spring_005fmessage_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f1[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f1.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f1.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f2(javax.servlet.jsp.tagext.JspTag _jspx_parent, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f2 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f2.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f2.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
    // /WEB-INF/jsp/administration/dashboard.jsp(41,7) name = code type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f2.setCode("log-netcas.path");
    // /WEB-INF/jsp/administration/dashboard.jsp(41,7) name = var type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f2.setVar("Lost");
    int[] _jspx_push_body_count_spring_005fmessage_005f2 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f2 = _jspx_th_spring_005fmessage_005f2.doStartTag();
      if (_jspx_th_spring_005fmessage_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        throw new javax.servlet.jsp.SkipPageException();
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f2[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f2.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f2.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fvar_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f0.setParent(null);
    // /WEB-INF/jsp/administration/dashboard.jsp(69,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005furl_005f0.setValue("/resources/theme/js/jquery.mousewheel.js");
    int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
    if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
    _jspx_th_c_005furl_005f1.setParent(null);
    // /WEB-INF/jsp/administration/dashboard.jsp(70,13) name = value type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_c_005furl_005f1.setValue("/resources/theme/js/jquery.jscrollpane.min.js");
    int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
    if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
      return true;
    }
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f1);
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f3 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f3.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f3.setParent(null);
    // /WEB-INF/jsp/administration/dashboard.jsp(150,14) name = code type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f3.setCode("language.tags.0044.03");
    int[] _jspx_push_body_count_spring_005fmessage_005f3 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f3 = _jspx_th_spring_005fmessage_005f3.doStartTag();
      if (_jspx_th_spring_005fmessage_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f3[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f3.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f3.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f4 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f4.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f4.setParent(null);
    // /WEB-INF/jsp/administration/dashboard.jsp(180,17) name = code type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f4.setCode("language.tags.0044.04");
    int[] _jspx_push_body_count_spring_005fmessage_005f4 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f4 = _jspx_th_spring_005fmessage_005f4.doStartTag();
      if (_jspx_th_spring_005fmessage_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f4[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f4.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f4.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f5(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f5 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f5.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f5.setParent(null);
    // /WEB-INF/jsp/administration/dashboard.jsp(193,14) name = code type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f5.setCode("language.tags.0044.08");
    int[] _jspx_push_body_count_spring_005fmessage_005f5 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f5 = _jspx_th_spring_005fmessage_005f5.doStartTag();
      if (_jspx_th_spring_005fmessage_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f5[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f5.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f5.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_spring_005fmessage_005f6(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  spring:message
    org.springframework.web.servlet.tags.MessageTag _jspx_th_spring_005fmessage_005f6 = (org.springframework.web.servlet.tags.MessageTag) _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.get(org.springframework.web.servlet.tags.MessageTag.class);
    _jspx_th_spring_005fmessage_005f6.setPageContext(_jspx_page_context);
    _jspx_th_spring_005fmessage_005f6.setParent(null);
    // /WEB-INF/jsp/administration/dashboard.jsp(239,17) name = code type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
    _jspx_th_spring_005fmessage_005f6.setCode("language.tags.0044.04");
    int[] _jspx_push_body_count_spring_005fmessage_005f6 = new int[] { 0 };
    try {
      int _jspx_eval_spring_005fmessage_005f6 = _jspx_th_spring_005fmessage_005f6.doStartTag();
      if (_jspx_th_spring_005fmessage_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } catch (java.lang.Throwable _jspx_exception) {
      while (_jspx_push_body_count_spring_005fmessage_005f6[0]-- > 0)
        out = _jspx_page_context.popBody();
      _jspx_th_spring_005fmessage_005f6.doCatch(_jspx_exception);
    } finally {
      _jspx_th_spring_005fmessage_005f6.doFinally();
      _005fjspx_005ftagPool_005fspring_005fmessage_0026_005fcode_005fnobody.reuse(_jspx_th_spring_005fmessage_005f6);
    }
    return false;
  }

  private class Helper
      extends org.apache.jasper.runtime.JspFragmentHelper
  {
    private javax.servlet.jsp.tagext.JspTag _jspx_parent;
    private int[] _jspx_push_body_count;

    public Helper( int discriminator, javax.servlet.jsp.JspContext jspContext, javax.servlet.jsp.tagext.JspTag _jspx_parent, int[] _jspx_push_body_count ) {
      super( discriminator, jspContext, _jspx_parent );
      this._jspx_parent = _jspx_parent;
      this._jspx_push_body_count = _jspx_push_body_count;
    }
    public void invoke0( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write('\r');
      out.write('\n');
      out.write('	');
      //  tiles:putAttribute
      org.apache.tiles.jsp.taglib.PutAttributeTag _jspx_th_tiles_005fputAttribute_005f0 = (new org.apache.tiles.jsp.taglib.PutAttributeTag());
      _jsp_instancemanager.newInstance(_jspx_th_tiles_005fputAttribute_005f0);
      _jspx_th_tiles_005fputAttribute_005f0.setJspContext(_jspx_page_context);
      _jspx_th_tiles_005fputAttribute_005f0.setParent(_jspx_parent);
      // /WEB-INF/jsp/administration/dashboard.jsp(4,1) name = name type = java.lang.String reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_tiles_005fputAttribute_005f0.setName("body");
      _jspx_th_tiles_005fputAttribute_005f0.setJspBody(new Helper( 1, _jspx_page_context, _jspx_th_tiles_005fputAttribute_005f0, null));
      _jspx_th_tiles_005fputAttribute_005f0.doTag();
      _jsp_instancemanager.destroyInstance(_jspx_th_tiles_005fputAttribute_005f0);
      out.write('\r');
      out.write('\n');
      return;
    }
    public void invoke1( javax.servlet.jsp.JspWriter out ) 
      throws java.lang.Throwable
    {
      out.write("\r\n");
      out.write("\t\t<style>\r\n");
      out.write(" \t\t\t.n-body-content .page-wrapper  \r\n");
      out.write(" \t\t\t{ \r\n");
      out.write(" \t\t\t\tbackground-color: transparent; \r\n");
      out.write(" \t\t\t\tborder-style: none; \r\n");
      out.write(" \t\t\t\tmargin:0;\r\n");
      out.write(" \t\t\t} \r\n");
      out.write("\t\t\t.code{ \r\n");
      out.write("\t \t\t\twhite-space: nowrap;\t \t\t\t\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t\t.scroll-pane\r\n");
      out.write("\t\t\t{\r\n");
      out.write("\t\t\t\twidth: 100%; \r\n");
      out.write("\t\t\t\theight: 600px;\r\n");
      out.write(" \t\t\t\toverflow: auto; \r\n");
      out.write("\t\t\t}\r\n");
      out.write(" \t\t\t.col-sm-11{\r\n");
      out.write(" \t\t\t\tpadding-right: 0px; \r\n");
      out.write(" \t\t\t\tpadding-left: 3px; \r\n");
      out.write(" \t\t\t}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t\t<div id=\"page1\" class=\"container-fluid page-wrapper\">\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12\" style=\"padding-right: 0px; padding-left: 0px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"card3\" class=\"col-xs-12 n-card StyloPanel\" >\r\n");
      out.write("\t\t\t\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"col-sm-6 panel-heading StyloPanel\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<h4 class=\"panel-title\"><b>");
      if (_jspx_meth_spring_005fmessage_005f0(_jspx_parent, _jspx_page_context))
        return;
      out.write("</b></h4>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div style=\"text-align: Right\" class=\"col-sm-6 StyloPanel \">\r\n");
      out.write(" \t\t\t\t\t\t\t\t<div id=\"radioBtn\" class=\"btn-group\">\r\n");
      out.write(" \t\t\t    \t\t\t\t\t<a class=\"btn btn-primary btn-sm active\" data-toggle=\"executionType\" data-title=\"S3m14ut0m4t1c\">");
      if (_jspx_meth_spring_005fmessage_005f1(_jspx_parent, _jspx_page_context))
        return;
      out.write("</a> \r\n");
      out.write(" \t    \t\t\t\t\t\t</div> \r\n");
      out.write("\t   \t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t<div id=\"divExterno\" class=\"row margen\" style=\"height: 600px;\" >\r\n");
      out.write("\t\t\t\t\t\t\t");
      if (_jspx_meth_spring_005fmessage_005f2(_jspx_parent, _jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div id=\"Panel_Log\"  class=\"scroll-pane code\"> \r\n");
      out.write("\t\t\t\t\t\t\t\t<p id=parrafo style=\"width: 100%\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");
      //  tagtail:tail
      com.cj.tail.tailTag _jspx_th_tagtail_005ftail_005f0 = (com.cj.tail.tailTag) _005fjspx_005ftagPool_005ftagtail_005ftail_0026_005fid_005ffile_005fcount.get(com.cj.tail.tailTag.class);
      _jspx_th_tagtail_005ftail_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tagtail_005ftail_005f0.setParent(new javax.servlet.jsp.tagext.TagAdapter((javax.servlet.jsp.tagext.SimpleTag) _jspx_parent));
      // /WEB-INF/jsp/administration/dashboard.jsp(44,9) name = file type = null reqTime = true required = true fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_tagtail_005ftail_005f0.setFile((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${Lost}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/administration/dashboard.jsp(44,9) name = count type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_tagtail_005ftail_005f0.setCount(1000);
      // /WEB-INF/jsp/administration/dashboard.jsp(44,9) name = id type = null reqTime = true required = false fragment = false deferredValue = false deferredMethod = false expectedTypeName = null methodSignature = null 
      _jspx_th_tagtail_005ftail_005f0.setId("S");
      int _jspx_eval_tagtail_005ftail_005f0 = _jspx_th_tagtail_005ftail_005f0.doStartTag();
      if (_jspx_eval_tagtail_005ftail_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tagtail_005ftail_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.pushBody();
          _jspx_th_tagtail_005ftail_005f0.setBodyContent((javax.servlet.jsp.tagext.BodyContent) out);
          _jspx_th_tagtail_005ftail_005f0.doInitBody();
        }
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t<p id=parrafo01>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t\t");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${S}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("<br>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t</p>\r\n");
          out.write("\t\t\t\t\t\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_tagtail_005ftail_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tagtail_005ftail_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tagtail_005ftail_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        _005fjspx_005ftagPool_005ftagtail_005ftail_0026_005fid_005ffile_005fcount.reuse(_jspx_th_tagtail_005ftail_005f0);
        throw new javax.servlet.jsp.SkipPageException();
      }
      _005fjspx_005ftagPool_005ftagtail_005ftail_0026_005fid_005ffile_005fcount.reuse(_jspx_th_tagtail_005ftail_005f0);
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</p> \r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\t\t\t\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-6\" style=\"padding-right: 0px; padding-left: 0px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"card1\" class=\"col-12 n-card amcharts-main-div\" style=\"position: relative; width: 100%; height: 0%;\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-xs-12 col-md-6\" style=\"padding-right: 0px; padding-left: 3px;\">\r\n");
      out.write("\t\t\t\t\t<div id=\"card2\" class=\"col-12 n-card\"></div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t");
      return;
    }
    public void invoke( java.io.Writer writer )
      throws javax.servlet.jsp.JspException
    {
      javax.servlet.jsp.JspWriter out = null;
      if( writer != null ) {
        out = this.jspContext.pushBody(writer);
      } else {
        out = this.jspContext.getOut();
      }
      try {
        Object _jspx_saved_JspContext = this.jspContext.getELContext().getContext(javax.servlet.jsp.JspContext.class);
        this.jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,this.jspContext);
        switch( this.discriminator ) {
          case 0:
            invoke0( out );
            break;
          case 1:
            invoke1( out );
            break;
        }
        jspContext.getELContext().putContext(javax.servlet.jsp.JspContext.class,_jspx_saved_JspContext);
      }
      catch( java.lang.Throwable e ) {
        if (e instanceof javax.servlet.jsp.SkipPageException)
            throw (javax.servlet.jsp.SkipPageException) e;
        throw new javax.servlet.jsp.JspException( e );
      }
      finally {
        if( writer != null ) {
          this.jspContext.popBody();
        }
      }
    }
  }
}
